/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bluelocker;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Jtdav
 */
public class BlueLocker extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public BlueLocker() {
        connected = false;
        currentdirectory = null;
        currentzippeddirectory = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pairbutton = new javax.swing.JButton();
        selectfolder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        currentdirectorylabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pairbutton.setText("Pair");
        pairbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pairbuttonActionPerformed(evt);
            }
        });

        selectfolder.setText("Select Folder");
        selectfolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectfolderActionPerformed(evt);
            }
        });

        jLabel1.setText("Current Folder:");

        currentdirectorylabel.setText("<Please select a folder>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectfolder, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pairbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(currentdirectorylabel)))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pairbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectfolder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentdirectorylabel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pairbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pairbuttonActionPerformed
        if (currentdirectory == null && currentzippeddirectory == null)
        {
            JOptionPane.showMessageDialog(this, "Please select a folder before pairing.");
            return;
        }
        
        connected = true;
        
        Pinger ping = new Pinger(this);
        ping.start();
    }//GEN-LAST:event_pairbuttonActionPerformed

    public void ReCallLockListener()
    {
        new Locker(this).start();
    }
    
    private void selectfolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectfolderActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.showOpenDialog(this);
        
        String file;
        
        try {file = chooser.getSelectedFile().getName();}
        catch (NullPointerException e) {return;}
        
        String ext = file.substring(file.length() - 4);
        
        if (ext.equals(".aes"))
        {
            System.out.println("Encrypted file chosen");
            currentzippeddirectory = chooser.getSelectedFile();
            currentdirectorylabel.setText(currentzippeddirectory.getAbsolutePath());
            ZipandEncrypt = new CompAndSec(currentzippeddirectory, true);
        }
        else if(!ext.contains("."))
        {
            System.out.println("Folder Chosen");
            currentdirectory = chooser.getSelectedFile();
            currentdirectorylabel.setText(currentdirectory.getAbsolutePath());
            ZipandEncrypt = new CompAndSec(currentdirectory, false);
        }
        else
            JOptionPane.showMessageDialog(this, "You did not select a folder or .AES file.\nPlease try again.");
    }//GEN-LAST:event_selectfolderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlueLocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            BlueLocker blueLocker = new BlueLocker();
            blueLocker.setLocationRelativeTo(null);
            blueLocker.setVisible(true);
        });
    }
    
    public void ToggleConnected()
    {
        connected = !connected;
        
        synchronized(this) {notifyAll();}
    }
    
    public boolean getConnected()
    {
        return connected;
    }
    
    public int Decompress()
    {
        return ZipandEncrypt.decompress();
    }
    
    public int Compress()
    {
        return ZipandEncrypt.compress();
    }
    
    public int Encrypt(String key)
    {
        return ZipandEncrypt.encrypt(key);
    }
    
    public int Decrypt(String key)
    {
        return ZipandEncrypt.decrypt(key);
    }
    
    //Our variables
    private File currentdirectory;
    private File currentzippeddirectory;
    private boolean connected;
    private CompAndSec ZipandEncrypt;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentdirectorylabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pairbutton;
    private javax.swing.JButton selectfolder;
    // End of variables declaration//GEN-END:variables
}
